from datetime import datetime

def clean_nmap(output: str):
    """
    Removes nmap service fingerprint noise from scan output.
    Fingerprint lines (SF-, SF:, NEXT SERVICE FINGERPRINT) add no value
    to a human-readable report and significantly bloat the output.
    Returns a clean string with only relevant scan results.
    """
    list_output = output.split("\n")
    filter_output = []
    for line in list_output:
        # Skip fingerprint data lines generated by -sV service detection
        if "SF:" in line or "NEXT SERVICE" in line or "SF-" in line:
            pass
        else:
            filter_output.append(line)
    return "\n".join(filter_output)


def gen_report(target: str, nmap_out: str, gobuster_out: str, nikto_out: str, virustotal: dict, abuseipdb: dict):
    """
    Generates the master report file (report.txt) combining all scan results
    and threat intelligence enrichment data into a single structured document.
    """
    time = datetime.now()
    time = time.strftime('%Y-%m-%d %H:%M:%S')

    with open("report.txt", "w") as file:
        # Report header
        file.write(f"{time}\n")
        file.write(f"Scanned host {target}\n")
        file.write("Generated by Aegis scanner using nmap,gobuster,nikto,virus total,abuseipdb,gemini\n")

        # Nmap scan — cleaned to remove fingerprint noise
        file.write("=" * 60)
        file.write("\nNmap scan:\n")
        file.write(clean_nmap(nmap_out))

        # Gobuster directory enumeration results
        file.write("=" * 60)
        file.write("\nGobuster scan:\n")
        file.write(gobuster_out)

        # Nikto web vulnerability scan results
        file.write("=" * 60)
        file.write("\nNikto scan:\n")
        file.write(nikto_out)

        # VirusTotal IP reputation — malicious/suspicious verdict counts
        file.write("=" * 60)
        file.write("\nVirus total:\n")
        if virustotal["error"] == None:
            file.write(f"malicious: {virustotal['malicious']}\n")
            file.write(f"suspicious: {virustotal['suspicious']}\n")
            file.write(f"harmless: {virustotal['harmless']}\n")
            file.write(f"undetected: {virustotal['undetected']}\n")
        else:
            file.write(f"An error occured: {virustotal['error']}\n")

        # AbuseIPDB confidence score — 0 (clean) to 100 (highly abusive)
        file.write("=" * 60)
        file.write("\nAbuseipdb:\n")
        if abuseipdb["error"] == None:
            file.write(f"abuse confidence score: {abuseipdb['abuseConfidenceScore']}\n")
        else:
            file.write(f"An error occured: {abuseipdb['error']}\n")
