from datetime import datetime


def clean_nmap(output:str):
    list_output = output.split("\n")
    filter_output = []
    for line in list_output:
        if "SF:" in line or "NEXT SERVICE" in line:
            pass
        else:
            filter_output.append(line)
    return "\n".join(filter_output)


def gen_report(target:str,nmap_out:str,gobuster_out:str,nikto_out:str,virustotal:dict,abuseipdb:dict):
    time = datetime.now()
    time = time.strftime('%Y-%m-%d %H:%M:%S')

    with open("report.txt","w") as file:
        file.write(f"{time}\n")
        file.write(f"Scanned host {target}\n")
        file.write("Generated by Aegis scanner using nmap,gobuster,nikto\n")

        # Nmap scan
        file.write("=" * 60)
        file.write("\nNmap scan:\n")
        file.write(clean_nmap(nmap_out))

        # gobuster scan
        file.write("=" * 60)
        file.write("\nGobuster scan:\n")
        file.write(gobuster_out)

        # nikto scan
        file.write("=" * 60)
        file.write("\nNikto scan:\n")
        file.write(nikto_out)

        # virus total scan
        file.write("=" * 60)
        file.write("\nVirus total:\n")

        if virustotal["error"] == None:
            file.write(f"malicious: {virustotal['malicious']}\n")
            file.write(f"suspicious: {virustotal['suspicious']}\n")
            file.write(f"harmless: {virustotal['harmless']}\n")
            file.write(f"undetected: {virustotal['undetected']}\n")
        else:
            file.write(f"An error occured: {virustotal['error']}\n")
        
        # abuseipdb scan
        file.write("=" * 60)
        file.write("\nAbuseipdb:\n")

        if abuseipdb["error"] == None:
            file.write(f"abuse confidence score: {abuseipdb['abuseConfidenceScore']}\n")
        else:
            file.write(f"An error occured: {abuseipdb['error']}\n")
    
