from datetime import datetime


def gen_report(target:str,nmap_out:str,gobuster_out:str,nikto_out:str):
    time = datetime.now()
    time = time.strftime('%Y-%m-%d %H:%M:%S')

    with open("report.txt","w") as file:
        file.write(f"{time}\n")
        file.write(f"Scanned host {target}\n")
        file.write("Generated by Aegis scanner using nmap,gobuster,nikto\n")

        file.write("=" * 60)
        file.write("\nNmap scan:\n")
        file.write(nmap_out)

        file.write("=" * 60)
        file.write("\nGobuster scan:\n")
        file.write(gobuster_out)

        file.write("=" * 60)
        file.write("\nNikto scan:\n")
        file.write(nikto_out)

        # virus total scan
        file.write("=" * 60)
        file.write("\nVirus total:\n")
        for key in virustotal:
            if key == "error" and virustotal[key] !=None:
                file.write(f"Error: {virustotal['error']}")
                break
            else:
                file.write(virustotal[key])
        
        # abuseipdb scan
        file.write("=" * 60)
        file.write("\nAbuseipdb:\n")
        for key in abuseipdb:
            if key == "error" and abuseipdb[key] !=None:
                file.write(f"Error: {abuseipdb['error']}")
                break
            else:
                file.write(abuseipdb[key])
